### ISSUE TITLE
Processor for adding field(s)

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/datapackage-pipelines#103]
As a dpp user, I want to add a new column to my existing data with the result of various operations (like sum, avg, min, max, multiply, constant, join, format) performed on values of pre-defined columns of the same row, so that after running `dpp run xxx` output data has new column with value calculated for me.

## Acceptance Criteria

* [ ] able to add new column to data
* [ ] able to perform operations like sum, avg, min, max, multiply, constant, join, format

## Tasks

* [ ] prepare specs
* [ ] wtire tests
* [ ] write processor `add_fields`
* [ ] update README

## Analysis 

Spec: 

```
run: add_fields
parameters:
  resources: resource_name
  fields:
    - operation: sum
      target: new_column_name
      nullas: 0 (default)
      type: any (default)
      columns
        - column1
        - column2
    - operation: sum
      target: another_column_name
      columns:
        - column3
        - column1
    - operation: sum
      target: total_sum
      columns:
        - new_column_name
        - another_column_name
    - operation: avg/min/max/multiply/join: same as for sum
    - operation: format
      target: new_column_name
      formated-string: '{column1} is better than {column2}'
```

Available operations:

* constant - add a constant value
* sum - summed value for given column(s) in a row. None -> 0
* avg - average value from given column(s) in a row. None -> 0
* min - min value among given column(s) in a row. None -> 0
* max - max value among given column(s) in a row. None -> 0
* multiply - product of given columns(s) in a row None -> 0
* join - joins two or more column values in a row (separated by comma)
* format - allows to pass the formatted string. Eg ‘my name is {first_name}’

**Comment by OriHoch** [comment]
sounds good and will be very useful I think, I also encountered some use-cases for this type of processing.

I would change the operations to be a list which will allow to use previous calculated columns as input for next operations.

```
run: add_colmuns
parameters:
  resources: resource_name
  fields:
    - operation: sum
      target: new_column_name
      nullas: 0 (default)
      type: any (default)
      columns
        - column1
        - column2
    - operation: sum
      target: another_column_name
      columns:
        - column3
        - column1
    - operation: sum
      target: total_sum
      columns:
        - new_column_name
        - another_column_name
```

**Comment by zelima** [comment]
@OriHoch great sounds better - updated spec and added some details about each operation. Will do PR

**Comment by zelima** [comment]
FIXED
