### ISSUE TITLE
Unpivot  tabular data

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/datapackage-pipelines#108]
As a dpp user, I want to unpivot or transpose my tabular data so that there's only one record per row

As a dpp user, I have data that has dates as  column names and I want to "unpivot" and have nice time series data so that I can easily reuse it for plotting graphs

Example:

```
# Pivoted data
country  	2005	2006	2007	
Afghanistan	46.6	46.9	47.2	
Albania	        76.1	76.3	76.5	
...

# Unpivoted data
country      year  average_age
Afghanistan  2005  46.6
Afghanistan  2006  46.9
Afghanistan  2007  47.2
Albania      2005  76.1
Albania      2006  76.3
Albania      2007  76.5
...
```

## Acceptance criteria

* [ ] Able to normalize my pivoted data
* [ ] `dpp run un-pivot-processor` provides valid datapackage 
* [ ] Able to pre define the name of columns to insert values

## Tasks

* [x] Do analysis
* [x] Prepare Spec
* [x] Failing Tests for processor
* [x] Create unpivot processor
* [ ] Passing test
* [ ] update REAMDE

## Analysis 

Example Spec for given data:
```
# data
country,2015 income,2015 expenses,2016 income,2016 expenses
xxx,20000,15000,30000,30000
...

# spec
- run: unpivot
  parameters:
    resources: (same as always)
    extraKeyFields:
      -
        name: year
        type: integer
      -
        name: direction
        name: string
    extraValueField:
        name: amount
        type: number
    unpivot:
      - 
        name: 2015 incomes
        keys:
          year: 2015
          direction: In
      - 
        name: 2015 expenses
        keys:
          year: 2015
          direction: Out
      - 
        name: 2016 incomes
        keys:
          year: 2016
          direction: In
      - 
        name: 2016 expenses
        keys:
          year: 2015
          direction: Out
      # or regex 
      -
        name: ([0-9]{4}) (\w+)
        keys:
          year: \1
          direction: \2
```

**Comment by rufuspollock** [comment]
@zelima how do you handle null of empty field values when unpivoting? Can you document this?

@akariv is there any document of how you can use this? Can you use these functions outside of dpp (i.e. can i use them directly in my own python code?)

**Comment by zelima** [comment]
@rufuspollock Empty values remain empty. Eg
```
city,2015,2016,2017
Londo,100,200,300
Paris,,100,200

will be transformed into this ==>

city,year,amount
London,2015,100
London,2016,200
London,2017,300
Paris,2015,
Paris,2016,200
Paris,2017,300
```

**Comment by rufuspollock** [comment]
@zelima it would be usual when unpivoting to strip empty values since they are an artefact of the pivoted data (you have to have an empty value because the columns are there). /cc @akariv what do you think?

**Comment by rufuspollock** [comment]
@akariv are you able to answer my earlier question:

> @akariv is there any document of how you can use this? Can you use these functions outside of dpp (i.e. can i use them directly in my own python code?) Motivation: i'm unpivoting some data myself and i don't need the full weight of dpp right now, but i would love to have a prebuilt, pre-tested algorithm i could use.

**Comment by akariv** [comment]
Re keeping 'empty' cells - that's a good suggestion.
We should add a parameter to control that (I'll add an issue for that).

Re using the processor - there's a section in the Readme with some
examples.
While it's possible to extract a processor's logic to a class and make it
importable, there is no standard way of doing so (and perhaps we should add
one).
As for the unpivot processor it's not the case atm, but not hard to do.
Either way it would still remain a dpp processor - meaning it's working on
a stream of rows which are described by a datapackage descriptor. If this
fits your use case, then you could use it locally.

**Comment by rufuspollock** [comment]
@akariv 

>While it's possible to extract a processor's logic to a class and make it
importable, there is no standard way of doing so (and perhaps we should add
one).

Big 👍 on doing this.

> Either way it would still remain a dpp processor - meaning it's working on
a stream of rows which are described by a datapackage descriptor. If this
fits your use case, then you could use it locally.

**Exactly** what I want. I think this is worth standardizing as an API / concept so that you can use this stuff outside of dpp.
